# Generated by Django 4.0.1 on 2024-03-10 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0004_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('post_name', models.CharField(max_length=70)),
                ('post_cat', models.CharField(max_length=70)),
                ('post_publish_date', models.DateField()),
            ],
        ),
    ]
