# Generated by Django 4.0.1 on 2024-03-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
